DROP TABLE IF EXISTS user;

DROP TABLE IF EXISTS tempHum;

CREATE TABLE tempHum (
  id INT AUTO_INCREMENT PRIMARY KEY,
  time DATETIME,
  temperature INT,
  humidity INT
);

CREATE TABLE user (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  age INT
);