DROP TABLE IF EXISTS user;

DROP TABLE IF EXISTS tempHum;

CREATE TABLE tempHum (
  id INT AUTO_INCREMENT PRIMARY KEY,
  time DATETIME,
  temperature DECIMAL(10, 8),
  humidity DECIMAL(10, 8),
  lux DECIMAL(10, 8),
);

CREATE TABLE user (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  age INT
);